### ISSUE TITLE
Fails at TASK [letsencrypt : register Let's Encrypt certificate with DNS challenge]

### ISSUE THREAD

**Issue by reelsense** [systemli/ansible-role-letsencrypt#11]
I'm having a problem using this role with https://github.com/systemli/ansible-role-mumble

```yaml
TASK [letsencrypt : register Let's Encrypt certificate with DNS challenge]
fatal: [instance-2a]: FAILED! => {
    "msg": "The conditional check 'not \"no action taken\" in letsencrypt_reg_certbot_dns.stdout' failed. The error was: error while evaluating conditional (not \"no action taken\" in letsencrypt_reg_certbot_dns.stdout): Unable to look up a name or access an attribute in template string ({% if not \"no action taken\" in letsencrypt_reg_certbot_dns.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"
}
```

**Comment by doobry-systemli** [comment]
Can you give a bit more context? Did you setup and test the DNS challenge environment (dynamic DNS zone, uupdate keys, ...)?

The error looks like if `letsencrypt_reg_certbot_dns` doesn't contain the key `stdout`, which would mean that the command in task `register Let's Encrypt certificate with DNS challenge` was not executed.

**Comment by reelsense** [comment]
Sorry I haven't had time to come back to this. I'll reopen if I have more time and have an answer.
