### ISSUE TITLE
Doesn't fail when DNS isn't configured for vhost

### ISSUE THREAD

**Issue by MrAlci** [systemli/ansible-role-letsencrypt#12]
We have a problem with multiple domains that we want to configure.

It continuous the task when 1 domain fails. We have fixed this with  failed_when: "'failed' in letsencrypt_reg_certbot_http.stderr". Do you have a better solution or a another methode?

If this is the good way, can you apply this on your letsencrypt role.

Output:
{
    "_ansible_parsed": true,
    "stderr_lines": [
        "Saving debug log to /var/log/letsencrypt/letsencrypt.log",
        "Plugins selected: Authenticator webroot, Installer None",
        "Renewing an existing certificate",
        "Performing the following challenges:",
        "http-01 challenge for deployservertest2.hosted-power.com",
        "http-01 challenge for deployservertest.hosted-power.com",
        "Using the webroot path /var/www/letsencrypt for all unmatched domains.",
        "Waiting for verification...",
        "Challenge failed for domain deployservertest.hosted-power.com",
        "Cleaning up challenges",
        "Performing the following challenges:",
        "http-01 challenge for deployservertest2.hosted-power.com",
        "Using the webroot path /var/www/letsencrypt for all unmatched domains.",
        "Waiting for verification...",
        "Cleaning up challenges",
        "Running deploy-hook command: /root/letsencryptrenew.bash"
    ],

Letsencrpyt role tasks (register):
- name: register Let's Encrypt certificate with HTTP challenge
  command: >
    certbot certonly
    {{ letsencrypt_opt_http_auth|default() }}
    {{ letsencrypt_opt_cert_name|default() }}
    {{ letsencrypt_opt_test_cert|default() }}
    {{ letsencrypt_cert.opts_extra|default(letsencrypt_opts_extra|default()) }}
    --domains {{ letsencrypt_cert.domains|join(',') }}
    --keep-until-expiring --expand --allow-subset-of-names
    --non-interactive --agree-tos
    {{ letsencrypt_opt_renew_hook|default() }}
  when: letsencrypt_cert.challenge|default() == 'http' and letsencrypt_cert.domains|default()
  register: letsencrypt_reg_certbot_http
  changed_when: not "no action taken" in letsencrypt_reg_certbot_http.stdout
  failed_when: "'failed' in letsencrypt_reg_certbot_http.stderr"

**Comment by HOSTED-POWER** [comment]
I wonder if we couldn't make "allow-subset-of-names" optional (configurable in the role) and what the influence of it would be (for example on renewals)

**Comment by HOSTED-POWER** [comment]
PS: Just checked, allow_subset_of_names is used for renewal, I think it's preferred to keep it there. 

For register of new cert, it probably would be best to fail if all domains can't be secure, otherwise the ansible role will succeed, customer thinks all is fine, but in fact certain domains are insecure (and not working).

**Comment by t2d** [comment]
> For register of new cert, it probably would be best to fail if all domains can't be secure, otherwise the ansible role will succeed, customer thinks all is fine, but in fact certain domains are insecure (and not working).

Yes, this happened to me in the past and I only recognized it because ansible was doing the step again in every run.

**Comment by doobry-systemli** [comment]
Thanks for your comments! I just pushed commits 3ead08f and 488001d that make `allow-subset-of-names` configurable. You now can change the default by setting `letsencrypt_subset_names: False` or change the behaviour for a single certificate by setting `subset_names: False` in the certificate variable.

Please let me know whether that fixes the issue for you.

**Comment by HOSTED-POWER** [comment]
Thanks a lot for looking into this!!

Well while it's a solution, I'm not sure it's preferred to have it off. When it's off, renewal's will fail way easier as well ...

I would prefer a SOLID check on server setup , but for renewal the allow-subset-of-names is probably preferred since it might change a bit after server was setup.

**Comment by doobry-systemli** [comment]
Unfortunately certbot doesn't support to fail only when invoked manually (or when obtaining the certificate for the first time).

You could add a check yourself in Ansible to verifiy that all requested domains ended up in the certificate. Just add a task like the following after your `include_role: systemli.letsencrypt`:

```
# This task fails if the subject altnames in the cert are not correct
- name: check if subject_altnames of certficates are correct
  openssl_certificate:
    path: "/etc/letsencrypt/live/{{ letsencrypt_cert.name }}/cert.pem"
    provider: assertonly
    subject_alt_name: "{{ letsencrypt_cert.domains }}"
```
