### ISSUE TITLE
Allow account without email

### ISSUE THREAD

**Issue by HOSTED-POWER** [systemli/ansible-role-letsencrypt#14]
Hi,

We use extra paramteter:  --register-unsafely-without-email 

However it interferes with account creation. In the past we managed to skip it better.

Could you fix it somehow that we can also generate certs without email? We're not interested at all in getting any email feedback ever :)

**Comment by HOSTED-POWER** [comment]
PS: I see you also removed: letsencrypt_cert.opts_extra

We really needed that one :|

**Comment by HOSTED-POWER** [comment]
PS PS: It would be great if we could also use --manual. We need it for ha setups where we install our own scripts for renewal :)

**Comment by t2d** [comment]
Thank you for your interest in our services. Systemli.org is a group of volunteers providing internet services for progressive movements. Therefore, our code and services are not intended for commercial usage and we don't provide any support for this use-case. However, pull request are welcome and will be reviewed as soon as possible.

**Comment by xshadow** [comment]
Fixed in #56
