### ISSUE TITLE
Role requires multiple plays to complete

### ISSUE THREAD

**Issue by goetzk** [systemli/ansible-role-letsencrypt#15]
Hi,
I'm wondering if you are willing to include a change like the one below from @kmille to remove the two part setup of this role.

https://github.com/kmille/ansible-role-letsencrypt/commit/e2ed4505676f4d86c09d87c91106c63b6977327d

Detailed background:
It turns out this play requires two runs: first with no configuration then one with the certificates to set up.
In the example below, the first play is only required so letsencrypt_cert can be empty during install.

~~~
 cat playbook.yaml
---

- hosts: example.com
  vars:
    letsencrypt_cert: []
  roles:
  - weareinteractive.apt
  - systemli.letsencrypt

- hosts: example.com
  roles:
  - systemli.letsencrypt
  - weareinteractive.nginx


 cat host_vars/example.com
---
apt_packages:
  - zip
  - nginx

# [nginx config]

letsencrypt_account_name: 'example@example'
letsencrypt_account_email: "{{ letsencrypt_account_name }}"
letsencrypt_http_auth: standalone
letsencrypt_dns_challenge: no
# Should probably try and fiddle things so this works
letsencrypt_group: no

letsencrypt_cert:
  name: "{{ bitwarden_domain }}"
  domains:
    - "{{ bitwarden_domain }}"
  challenge: http
  http_auth: standalone
```

**Comment by t2d** [comment]
I think we're open to the idea. However, we would like to keep the ability to skip the set part and just do certs. The reason is, we're using `include_role` many times and would like to have this fast. My idea would be to introduce a variable like `letencrypt_setup_skip` that I could set to improve performance. But change the default behavior to install packages and create certificates. Could you try to implement this?

**Comment by goetzk** [comment]
Sure, that sounds like a reasonable option.
I will try and send a PR tonight my time.

Karl

On 3 May 2020 02:28:21 GMT+10:00, t2d <notifications@github.com> wrote:
>I think we're open to the idea. However, we would like to keep the
>ability to skip the set part and just do certs. The reason is, we're
>using `include_role` many times and would like to have this fast. My
>idea would be to introduce a variable like `letencrypt_setup_skip` that
>I could set to improve performance. But change the default behavior to
>install packages and create certificates. Could you try to implement
>this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/systemli/ansible-role-letsencrypt/issues/15#issuecomment-622979318

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
This is now PR #16.
