### ISSUE TITLE
Create rewrite to /var/www/letsencrypt for `.well-known/acme-challenge` in apache2

### ISSUE THREAD

**Issue by t2d** [systemli/ansible-role-letsencrypt#17]
Idea is like: https://stackoverflow.com/a/46251500
Would solve some bootstrapping problems

**Comment by neingeist** [comment]
we use this configuration at [querfunk](https://mp3.querfunk.de/qfhi):

~~~yaml
---
- hosts: mp3.querfunk.de
  remote_user: root

  pre_tasks:
    - name: check if in maintenance window
      command: stuff/in-maintenance-window
      delegate_to: localhost
      changed_when: false
      tags:
        - always


  tasks:
    - file:
        path: /var/lib/letsencrypt/webroot/
        state: directory
    - copy:
        dest: /etc/apache2/conf-available/letsencrypt.conf
        content: |
          Alias /.well-known/acme-challenge/ /var/lib/letsencrypt/webroot/.well-known/acme-challenge/
          <Directory "/var/lib/letsencrypt/">
              AllowOverride None
              Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
              Require method GET POST OPTIONS
          </Directory>
      notify: reload apache2
    - file:
        src:  ../conf-available/letsencrypt.conf
        dest: /etc/apache2/conf-enabled/letsencrypt.conf
        state: link
      notify: reload apache2

    # flush handlers so apache conf is enabled
    - meta: flush_handlers

    - include_role:
        name: letsencrypt

  handlers:
    - name: "reload apache2"
      service: name=apache2 state=reloaded
~~~

with these variables set:
~~~yaml
letsencrypt_account_email: "neingeist@querfunk.de"
letsencrypt_webroot_path: /var/lib/letsencrypt/webroot
letsencrypt_cert:
  name: mp3.querfunk.de
  domains:
    - mp3.querfunk.de
  challenge: http
  http_auth: webroot
  services:
    - apache2
~~~

this bootstraps fine.

**Comment by doobry-systemli** [comment]
I fully agree that this is a great idea to do, but it has to be implemented by the tasks/roles that configure the webserver and that *invoke* the letsencrypt role. In my eyes, we can do nothing about it inside this role.

**Comment by neingeist** [comment]
> I fully agree that this is a great idea to do, but it has to be implemented by the tasks/roles that configure the webserver and that _invoke_ the letsencrypt role. In my eyes, we can do nothing about it inside this role.

I agree.

However it's really tricky to bootstrap correctly¹, so maybe you want to provide an example?

¹  The above is only one half of it, when this playbook is run, the certificates are ready and a https service can be set up.

**Comment by doobry-systemli** [comment]
> However it's really tricky to bootstrap correctly¹, so maybe you want to provide an example?

I agree that an example in a dedicated section of the README would be nice to have. Could you write up one and submit a pull request? That would be super cool :slightly_smiling_face:
