### ISSUE TITLE
cant seem to get dns challange to work

### ISSUE THREAD

**Issue by vizonyc** [systemli/ansible-role-letsencrypt#28]
TASK [ansible-role-letsencrypt : register Let's Encrypt certificate with DNS challenge] ************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["certbot", "certonly", "--manual", "--cert-name", "vizotest", "--domains", "vizowuzherealso.iccchem.com", "--preferred-challenge=dns", "--keep-until-expiring", "--expand", "--allow-subset-of-names", "--non-interactive", "--agree-tos", "--manual-public-ip-logging-ok", "--manual-auth-hook", "certbot-dns-hook.sh auth", "--manual-cleanup-hook", "certbot-dns-hook.sh cleanup"], "delta": "0:00:28.315553", "end": "2021-05-25 11:58:09.918568", "msg": "non-zero return code", "rc": 1, "start": "2021-05-25 11:57:41.603015", "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator manual, Installer None\nObtaining a new certificate\nPerforming the following challenges:\ndns-01 challenge for vizowuzherealso.iccchem.com\nHook command \"certbot-dns-hook.sh auth\" returned error code 2\nError output from certbot-dns-hook.sh:\n; Communication with 160.72.174.202#53 failed: timed out\n\nWaiting for verification...\nChallenge failed for domain vizowuzherealso.iccchem.com\nCleaning up challenges\nHook command \"certbot-dns-hook.sh cleanup\" returned error code 2\nError output from certbot-dns-hook.sh:\n; Communication with 160.72.174.202#53 failed: timed out\n\nChallenges failed for all domains", "stderr_lines": ["Saving debug log to /var/log/letsencrypt/letsencrypt.log", "Plugins selected: Authenticator manual, Installer None", "Obtaining a new certificate", "Performing the following challenges:", "dns-01 challenge for vizowuzherealso.iccchem.com", "Hook command \"certbot-dns-hook.sh auth\" returned error code 2", "Error output from certbot-dns-hook.sh:", "; Communication with 160.72.174.202#53 failed: timed out", "", "Waiting for verification...", "Challenge failed for domain vizowuzherealso.iccchem.com", "Cleaning up challenges", "Hook command \"certbot-dns-hook.sh cleanup\" returned error code 2", "Error output from certbot-dns-hook.sh:", "; Communication with 160.72.174.202#53 failed: timed out", "", "Challenges failed for all domains"], "stdout": "", "stdout_lines": []}

I dont know why it doesnt complete. I makes all the appropriate records it seems, I cant seem to get it to finish

**Comment by t2d** [comment]
Did you have a look at the [requirements for DNS challenge](https://github.com/systemli/ansible-role-letsencrypt#the-dns-challenge)?

**Comment by vizonyc** [comment]
> Did you have a look at the [requirements for DNS challenge](https://github.com/systemli/ansible-role-letsencrypt#the-dns-challenge)?

Yes I have all that setup, I see the records being created and deleted during the run

**Comment by t2d** [comment]
Great! Can we close the issue then?

**Comment by vizonyc** [comment]
Yes thank you
