### ISSUE TITLE
Provide a variable for the letsencrypt directory

### ISSUE THREAD

**Issue by dustindortch** [systemli/ansible-role-letsencrypt#29]
The role is rather opinionated in that the letsencrypt must be `/etc/letsencrypt`.

It would be great to have that as a variable that could be defined, but use that directory as the default.  It makes it rather complicated to use it in a container by hardcoding the directory like that.

**Comment by t2d** [comment]
Thank you for raising this issue. A PR addressing this would certainly be welcome.

**Comment by doobry-systemli** [comment]
Fixed by https://github.com/systemli/ansible-role-letsencrypt/pull/78.
