### ISSUE TITLE
"Too many levels of symbolic links (40)"

### ISSUE THREAD

**Issue by strarsis** [systemli/ansible-role-letsencrypt#30]
When using this role in Vagrant, `rsync` fails because of "Too many levels of symbolic links (40)".
The error log also shows a recursive loop:
````
[...]/vendor/roles/letsencrypt_cert/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/default/roles/ansible-role-letsencrypt/molecule/[...]
````
What can be the reason for this?

**Comment by t2d** [comment]
What do you mean specifically by "using in Vagrant"?

**Comment by strarsis** [comment]
@t2d: Alright, Vagrant is using `rsync` by default for its default `vagrant` synced folder. 
`rsync` tries to resolve a symlink in the `molecule` that links to a role directories above.
That directory in turn contains the `moulecule` folder, resulting in a recursive loop that makes `rsync` abort after too many iterations.
The fix was to configure `rsync` to skip symlinks in that case (`--no-links`):
```yml
config.vm.synced_folder '.', '/vagrant', rsync__args: [ '--no-links' ]
````

**Comment by t2d** [comment]
I don't get why you have those soft links at all. If you want to test the role with Vagrant just use 'molecule test'. Otherwise the symlink looks like a rest of an old molecule session, maybe? It's not in the repo.
Glad you solved your problem anyway.

Am 29. August 2021 13:27:16 MESZ schrieb strarsis ***@***.***>:
***@***.***: Alright, Vagrant is using `rsync` by default for its default
>`vagrant` synced folder. 
>`rsync` tries to resolve a symlink in the `molecule` that links to a
>role directories above.
>That directory in turn contains the `moulecule` folder, resulting in a
>recursive loop that makes `rsync` abort after too many iterations.
>The fix was to configure `rsync` to skip symlinks in that case
>(`--no-links`):
>```yml
>config.vm.synced_folder '.', '/vagrant', rsync__args: [ '--no-links' ]
>````
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/systemli/ansible-role-letsencrypt/issues/30#issuecomment-907775710

-- Gesendet von /e/ Mail.
