### ISSUE TITLE
Support  --register-unsafely-without-email

### ISSUE THREAD

**Issue by HOSTED-POWER** [systemli/ansible-role-letsencrypt#4]
Hello,

We don't want to receive any emails regarding let's encrypt (certs are monitored via other means).

Would it be possible to support the option *--register-unsafely-without-email* which would avoid setting an email address at all? Thanks a lot!

**Comment by HOSTED-POWER** [comment]
Hi,

Thanks a lot for your changes!! We're very happy with the updated version!

However we have one remaining error with this check:

- name: check if letsencrypt_account_email is set
  fail:
    msg: "Error: letsencrypt_account_email required for account creation"
  when: not letsencrypt_account_email|default() and not __testing|default()

It's unnecessary since we don't want to specify email in this case.

And we had still issues with this (line 84 in tasks/install.yml):

    --email "{{ letsencrypt_account_email|default() }}"

**Comment by mejo-** [comment]
Hi @HOSTED-POWER, thanks for your feedback. I prepared an update in a separate branch [register_unsafely](https://github.com/systemli/ansible-role-letsencrypt/tree/register_unsafely). Unfortunately I don't have the time to do thorough testing at the moment. Could you give the branch a try and see whether it fixes the issues for you?

**Comment by mejo-** [comment]
Hi @HOSTED-POWER, thanks for your feedback. I prepared an update in a separate branch [register_unsafely](https://github.com/systemli/ansible-role-letsencrypt/tree/register_unsafely). Unfortunately I don't have the time to do thorough testing at the moment. Could you give the branch a try and see whether it fixes the issues for you?

**Comment by doobry-systemli** [comment]
Hi @HOSTED-POWER, thanks for your feedback. I prepared an update in a separate branch [register_unsafely](https://github.com/systemli/ansible-role-letsencrypt/tree/register_unsafely). Unfortunately I don't have the time to do thorough testing at the moment. Could you give the branch a try and see whether it fixes the issues for you?

**Comment by HOSTED-POWER** [comment]
Wow what a fast service, thanks! Good news: It works fine now it seems!
