### ISSUE TITLE
Remove `letsencrypt_webserver_groupname`?

### ISSUE THREAD

**Issue by cyroxx** [systemli/ansible-role-letsencrypt#51]
While working on #50, I found it rather surprising that I needed to make sure that a host that uses the `http` challenge needs to be in the correct `letsencrypt_webserver_groupname` (default: `web`).

What is the reasoning behind this?
Shouldn't it be enough that we choose the http challenge and set `letsencrypt_http_auth` if required?

**Comment by t2d** [comment]
I think you are right. Can you please prepare a PR and add @doobry-systemli as reviewer? Thanks!
