### ISSUE TITLE
Supported distributions and releases

### ISSUE THREAD

**Issue by akaihola** [systemli/ansible-role-letsencrypt#70]
The `README` doesn't state which Linux distributions and their releases this role supports as is tested on.

**Comment by t2d** [comment]
- Supported versions: https://github.com/systemli/ansible-role-letsencrypt/blob/main/meta/main.yml#L14
- Tested versions: https://github.com/systemli/ansible-role-letsencrypt/blob/main/.github/workflows/main.yml#L22

A PR to the `README.md` would be welcome.
